---
- name: Create a user and group with prompted username and group
  hosts: Ubuntu
  become: yes  # Equivalent to '-b' (run as root)
  vars_prompt:
    - name: "username"
      prompt: "Enter the username"
      private: no  # Don't mask the input
    - name: "group"
      prompt: "Enter the group"
      private: no  # Don't mask the input

  tasks:
    - name: Ensure the group exists
      group:
        name: "{{ group }}"
        state: present

    - name: Ensure the user exists and is in the group
      user:
        name: "{{ username }}"
        group: "{{ group }}"
        state: present

